name: openalex
description: A new Flutter package project.
version: 0.0.1
homepage: https://openalex.org/

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  json_annotation: ^4.8.1

# Build command
# flutter pub run build_runner build --delete-conflicting-outputs
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  json_serializable: ^6.7.1

flutter:

# https://dart.dev/tools/pub/pubspec#screenshots
screenshots:
  - description: "OpenAlex"
    path: assets/open_alex_logo.png

